### ISSUE TITLE
Angular 7 support

### ISSUE THREAD

**Issue by rebendajirijr** [srikanthonl/ngx-braintree#102]
Can you please add support for Angular 7? Thank you.

**Comment by RELAXccc** [comment]
angular 7 works fine, just change
`/node_modules/ngx-braintree/package.json`
peerDependencies to
`  "peerDependencies": {
    "@angular/common": "^6.0.0-rc.0 || ^7.0.0",
    "@angular/core": "^6.0.0-rc.0 || ^7.0.0"
  },`

seams like there were no changes from 6 to 7 that break this module

**Comment by rebendajirijr** [comment]
We need an official support.

**Comment by caroso1222** [comment]
I confirm this works just fine with Angular 7. Didn't need to change anything anywhere.

**Comment by peter-snr** [comment]
Hi everyone,

hope someone can help, I am getting a null pointer for my service in this code.

`
@Component({
  selector: 'payment-method',
  templateUrl: './payment-method.component.html',
  styleUrls: ['./payment-method.component.css']
})
export class PaymentMethodComponent implements OnInit {

  @Output('next')
  completed:EventEmitter<boolean> = new EventEmitter<boolean>();

  clientTokenUrl:string = `${environment.apiServerUrl}/payments`;
  clientPurchaseUrl:string = `${environment.apiServerUrl}/payments`;


  constructor(private paymentService:PaymentsService) { }


  createPurchase(nonce:string, chargeAmount: number): Observable<string> {
    console.log('Create Purchase, nonce: ', nonce);
    const btToken:BtToken = new BtToken('Test', 'User', nonce);
   // Getting a null for the paymentService below ??
    return this.paymentService.createSubscription(btToken);

  }
  onPaymentStatus(status:any) {
    console.log('Payment Status', status);
  }
}
`
And this template
`
<ngx-braintree
      [clientTokenURL]="clientTokenUrl"
      [createPurchaseURL]="clientPurchaseUrl"
      (paymentStatus)="onPaymentStatus($event)"
      [createPurchase]="createPurchase"
      [buttonText]="'Subscribe'"
      ></ngx-braintree>
`
Thanks if you can help :)

**Comment by srikanthonl** [comment]
Apologies for a late (very) response. ngx-braintree now supports Angular version 7 and 8. Please check the readme on how to install.
