### ISSUE TITLE
Support for Angular 8 applications

### ISSUE THREAD

**Issue by barsurfer** [srikanthonl/ngx-braintree#115]
It would be great to add Angular 8 support. It is not compatible right now at least because of the fact that deprecated DOCUMENT was removed from @angular/platform-browser. Tried to to resolve this in the pull request attached (Also fixed tests and performed some code linting).

**Comment by barsurfer** [comment]
@srikanthonl Any chance you can review the PR above?

**Comment by niraj-ui** [comment]
any guys solve this problem, i also facing this problem. Please Help me.

**Comment by drsinghal92** [comment]
If your file fesm2015/ngx-braintree.js
then you are import DOCUMENT in @angular/common.

**Comment by PugSQL** [comment]
Status of pull request? Is this module abandoned?

**Comment by srikanthonl** [comment]
Sorry for being late in replying as I'm extremely busy these days and not able to accommodate time for this package. Anyone interested in taking the ownership of this package? Please let me know.

**Comment by PugSQL** [comment]
Maybe @barsurfer is up for the task? Or in the meantime looking for new ownership just merge the barsurfers pull request? It's a great package and it would be really nice to be able to upgrade to Angular 8.

**Comment by mustahsanmustafa** [comment]
any update on this?

**Comment by niraj-ui** [comment]
> any update on this?

No, i leave

**Comment by srikanthonl** [comment]
Once again sorry for being late guys. Thank you @barsurfer for the pull request. Support for Angular 8 now available and published to npm.
