### ISSUE TITLE
StaticInjectorError[HttpClient]

### ISSUE THREAD

**Issue by Eimisg** [srikanthonl/ngx-braintree#35]
### ## I get StaticInjectorError when I add directive into template

```
ERROR Error: Uncaught (in promise): Error: StaticInjectorError[HttpClient]: 
  StaticInjectorError[HttpClient]: 
    NullInjectorError: No provider for HttpClient!
Error: StaticInjectorError[HttpClient]: 
  StaticInjectorError[HttpClient]: 
    NullInjectorError: No provider for HttpClient!
```

`"dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/cdk": "^5.0.2",
    "@angular/cli": "^1.6.3",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.2.0",
    "@angular/material": "^5.0.2",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@ngrx/store": "^@4.1.1",
    "angular-checkboxes": "^1.0.3",
    "braintree": "^2.4.0",
    "core-js": "^2.4.1",
    "devextreme": "^17.2.4",
    "devextreme-angular": "^17.2.4",
    "ng2-nouislider": "^1.7.4",
    "ngx-braintree": "^3.0.0",
    "ngx-order-pipe": "^1.1.0",
    "ngx-pagination": "^3.0.3",
    "nouislider": "^10.1.0",
    "rxjs": "^5.4.2",
    "swiper": "^4.0.7",
    "zone.js": "^0.8.14"
  },`

**Comment by srikanthonl** [comment]
Did u import HttpClientModule?
import { HttpClientModule } from '@angular/common/http';

and in @NgModule imports section add
HttpClientModule,

**Comment by Eimisg** [comment]
Yes, I followed example step by step

**Comment by srikanthonl** [comment]
Actually that's a straightforward error raised when a module isn't found. Can youplease post your module.ts file and the code where the ngx-braintree component is used?

**Comment by Eimisg** [comment]
Module.ts
`import {BrowserModule} from '@angular/platform-browser';
import {NgModule} from '@angular/core';
import {HttpClientModule} from '@angular/common/http';
import {AppRoutingModule} from './app-routing-module';
import {ProductModule} from './product/product.module';
import {StoreModule} from '@ngrx/store';
import {CartReducer} from './cart/store/cart.reducer';
import {AuthModule} from './auth/auth.module';
import {EffectsModule} from '@ngrx/effects';
import {AuthEffects} from './auth/store/auth.effects';
import {authReducer} from './auth/store/auth-reducers';
import {NgxBraintreeModule} from 'ngx-braintree';
...

@NgModule({
  declarations: [
    AppComponent,
    HeaderComponent,
    FooterComponent,
    HomeComponent,
    CartComponent,
    WishlistComponent,
    CheckoutComponent
  ],
  imports: [
    BrowserModule,
    HttpClientModule,
    EffectsModule.forRoot([AuthEffects]),
    AppRoutingModule,
    ProductModule,
    AuthModule,
    StoreModule.forRoot({cart: CartReducer, auth: authReducer}),
    MatStepperModule,
    MatFormFieldModule,
    BrowserAnimationsModule,
    FormsModule,
    ReactiveFormsModule,
    NgxBraintreeModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {
}
`
I am trying  <ngx-braintree
	[clientTokenURL]="'api/braintree/getclienttoken'"
	[createPurchaseURL]="'api/braintree/createpurchase'"
	(paymentStatus)="onPaymentStatus($event)">
</ngx-braintree> on empty template

**Comment by srikanthonl** [comment]
I have just created a new application and successfully ran with ngx-braintree. Unfortunately I'm unable to reproduce your error. Can you please try in a new application if possible and let me know?

**Comment by Eimisg** [comment]
I updated Angular packages and ngx-braintree itself and it started working. Thank you for really useful package!
