### ISSUE TITLE
handling failed purchase

### ISSUE THREAD

**Issue by sarora2073** [srikanthonl/ngx-braintree#37]
Hi,

Thanks for creating this package! 

I'm wondering if there is a way to handle the fail case after purchase i.e. after the 'createPurchaseUrl' is called, and the backend tries to process the transaction (or save the customer), if that fails (e.g. because the user made a typo,) I want the front-end to display the credit card entry screen again. Is there any mechanism in ngx-braintree to support this?

Thank you,

-S. Arora

**Comment by srikanthonl** [comment]
This has been handled in the version 3.3.0. Please update your ngx-braintree package. ngx-braintree now re-renders the UI on any transactional error and also displays the error. For more information please visit the paymentStatus section of the README file which outlines what is expected from your server response.

**Comment by sarora2073** [comment]
sweet! thank you again.
