### ISSUE TITLE
PayPal Vault support

### ISSUE THREAD

**Issue by mmoravcik** [srikanthonl/ngx-braintree#41]
Hi, this looks promising. 

Is there (planning to be) any support for PayPal Vault / recurring payments?

https://developers.braintreepayments.com/guides/paypal/vault/javascript/v3

**Comment by srikanthonl** [comment]
Hi mmoravcik,

ngx-braintree will be constantly improved with new features although there is no proritized feature plan list at this moment. An ongoing list of upcoming features (which might also include PayPal vault) will be updated in the README file soon. Please feel free to suggest any feature requests.

**Comment by sufiiiyan** [comment]
support for PayPal +1

**Comment by DeerBeer** [comment]
PayPal +1

**Comment by srikanthonl** [comment]
PayPal support is almost developed. Tomorrow’s release will include PayPal Checkout and PayPal Vault support.

**Comment by srikanthonl** [comment]
PayPal Checkout and PayPal Vault support is now available with today's release (v3.4.1)
