### ISSUE TITLE
Have a directive to only display Paypal payment method

### ISSUE THREAD

**Issue by caothangsstech** [srikanthonl/ngx-braintree#55]
For now, when set enablePaypalCheckout to true, it will show paypal payment methods in drop in which is great. But it also always show Credit Card payment in drop in too. What if i only want to show paypal payment method. Is there any directive to set it (Example: enableCreditCheckout = false).

Thank you so much for your wonderful work! You really saves my life!

![image](https://user-images.githubusercontent.com/37891313/38070165-aeed5746-3344-11e8-8ebf-45d1a70a3f39.png)

**Comment by srikanthonl** [comment]
Closing this as Braintree dropin UI definitely displays the credit card UI at a minimum.
