### ISSUE TITLE
Callback function when dropin is ready/loaded

### ISSUE THREAD

**Issue by superelement** [srikanthonl/ngx-braintree#59]
`braintree.dropin.create` accepts a callback function for when the component is fully loaded and ready. Would be good to have an option similar to `paymentStatus` to handle the 'ready'.

**Comment by srikanthonl** [comment]
@superelement Thanks for the feature request. Sorry for a late response. I was offline for a few weeks. Yes notifying the user when the dropin is loaded and ready via an event makes sense. This feature will be available by this weekend.

**Comment by srikanthonl** [comment]
This is now available in v6.1.2
