### ISSUE TITLE
How to check responce from Paypal Checkout?

### ISSUE THREAD

**Issue by CodeAnomalies** [srikanthonl/ngx-braintree#66]
I have enabled Paypal checkout but dont know how to check if the payment was successful or not.
this is my code.

**My Drop-in is working fine Just want to know how to handle Paypal Checkout Responce**

braintree.component.html
```
<ngx-braintree
    [clientTokenURL]="My API'" 
    [createPurchaseURL]="My API"
    [chargeAmount]="55.55"
    [buttonText]="'Pay'"
    (paymentStatus)="onPaymentStatus($event)"
    [enablePaypalCheckout] = "true"
    [currency]="'USD'">
</ngx-braintree>
```

braintree.component.ts
```
onPaymentStatus(braintreeResponce) {
	console.log('BrainTree Responce');
	console.log(braintreeResponce);
}
```

**Comment by srikanthonl** [comment]
The response the onPaymentStatus receives is whatever your server API that handled the purchase sends. So, your server should have a response from Braintree, before onPaymentStatus is called which gives you the response where you should find something like response.IsSuccessStatusCode which tells whether the transaction was a success. Its upto your api to decide what and how much details to return to ngx-braintree to make any decisions on the client side. ngx-braintree just receives whatever transaction response is sent by your server which you access via listening to paymentStatus event.

**Comment by srikanthonl** [comment]
As in documentation, ngx-braintree posts the nonce and the chargeAmount, to the URL you provide, in the following format:
{"nonce":"d7438dd5-7f14-0b2a-7a6f-f3c83d43b5b7","chargeAmount":55.55}

I see that your purchaseURL() function is trying to read the amount as data.amount shouldn't it be data.chargeAmount?

**Comment by CodeAnomalies** [comment]
my mistake on that.
I mistakenly wrote it wrong here, that is correct on my server, that is not an issue as when I pay with drop-in it works, the API is not being called when I pay with Paypal checkout and also the amount of payment is also not displayed on paypal checkout.

**Expected** 
![screen shot 2018-05-08 at 4 24 38 pm](https://user-images.githubusercontent.com/33337269/39753615-1556622c-52dd-11e8-9df3-39887ea4c111.png)

**Getting**
![screen shot 2018-05-08 at 4 25 35 pm](https://user-images.githubusercontent.com/33337269/39753631-2078a6a6-52dd-11e8-924c-c66235c70732.png)

**As you can see the amount is not being passed to paypal checkout**

**Comment by srikanthonl** [comment]
Well, ngx-braintree has no control on this window. Although it could configure this window to some extent for example, to show shipping address (which it currently is not doing yet), but AFAIK the amount is not displayed for paypal express checkout (the amount might get displayed for other types of paypal integrations but not for Paypal in Braintree DropIn UI). The visit to PayPal window is only to login and its back to your application after logging in where you can (or already are) displaying the amount to charge anyway.

**Comment by experionakash** [comment]
@CodeAnomalies how do you fixed this issue
