### ISSUE TITLE
Loader should be more generic

### ISSUE THREAD

**Issue by zolakt** [srikanthonl/ngx-braintree#67]
As mentioned in [another issue](https://github.com/srikanthonl/ngx-braintree/issues/56#issuecomment-385914450).
Loader directive is targeting an "img" element.
It should target something more generic, a CSS class or ID, or even better make it a directive.

**Comment by srikanthonl** [comment]
Loader is now 
less restrictive,
can be hidden if not needed, 
when buttons are content projected, setting buttonText is now not required.
