### ISSUE TITLE
Multiple Declaration Error after updating to angular 6

### ISSUE THREAD

**Issue by CodeAnomalies** [srikanthonl/ngx-braintree#71]
This is the error I get. 
```
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/ngx-braintree/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
```

**Comment by srikanthonl** [comment]
@CodeAnomalies support for Angular version 6 will be available in the the next version of ngx-braintree. By the mid of next week the next version will be released with several other bug fixes. This is being tracked via #68

**Comment by srikanthonl** [comment]
Support for Angular 6 applications now available with several other bug fixes. Please install ngx-braintree version 6.0.0
