### ISSUE TITLE
Angular 5 integration with Firebase

### ISSUE THREAD

**Issue by Ramya-Bronson** [srikanthonl/ngx-braintree#74]
Hi,
I want to integrate Braintree Suscription model with pure Angular 5 with Firebase.
I have installed the npm and have imported the module.
But I am unable to understand ,
<ngx-braintree 
  [clientTokenURL]="'api/braintree/getclienttoken'" 
  [createPurchaseURL]="'api/braintree/createpurchase'" 
  [chargeAmount]="55.55"
  (paymentStatus)="onPaymentStatus($event)">
</ngx-braintree>

what is clientTokenURL and createPurchaseURL? What do I need to do to proceed further?

**Comment by srikanthonl** [comment]
@Ramya-Bronson  clientTokenURL and createPurchaseURL are YOUR server side API end points. These are the URLs that get the client token from Braintree and handle purchase. These cannot be done on the client side and can only be done on the server side. Hence, you need to provide these end points to ngx-braintree to get data from and post data to. Examples of how and what to write in these server side methods can be found in the readme of ngx-braintree :) or in the braintree dropin integration documentation.
