### ISSUE TITLE
Notification event after users clicks pay and before nonce request is initiated

### ISSUE THREAD

**Issue by wslade64** [srikanthonl/ngx-braintree#75]
I have an app similar to motel booking. Once they have reserved the room a timer starts that enforces payment. I would like to stop the timer when the user clicks the pay button. Can the plugin fire an event when the pay button is clicked?

**Comment by srikanthonl** [comment]
Hi @wslade64 ,

A `paymentStatus ` event is fired after the user clicks Pay and the payment finishes. No, event is fired when the user clicks Pay and before the nonce is received. If you want to run some functionality as soon as the user clicks Pay please use the content projection feature of ngx-braintree. Please refer Point no. 13 of ngx-braintree readme file which explains how you can project your own buttons. You will be projecting a button like this `<button ngxPay>Purchase</button>` on which you will also be able to add a click event to stop your timer.
