### ISSUE TITLE
Add custom data to payment request

### ISSUE THREAD

**Issue by michaelauderer** [srikanthonl/ngx-braintree#76]
On my backend, I need my custom user ID to be sent along with the payment request. Currently there is no way to add this data to the request object.

I propose having an additional optional property, `purchaseData` which can be used to add extra data, like a UID, to the payment request.

**Comment by srikanthonl** [comment]
Hi,

Apologies for a delayed response. Was offline for 4 weeks.

This can be accomplished by passing in your own createPurchase function, through which you can send whatever data you want to your backend. Please refer to points 8 and 9 in the readme which explain on how to pass your own getclienttoken and createpurchase functions.
