### ISSUE TITLE
Support for CVV

### ISSUE THREAD

**Issue by szarkowicz** [srikanthonl/ngx-braintree#86]
Hi,

Let me start by saying thanks for creating this simple Angular plugin. Getting it up and running was pretty simple.

Question: Are you planning on supporting CVV ?

Thanks again
Sean

**Comment by srikanthonl** [comment]
Thank you. CVV can be configured in your Braintree account's Dashboard. #77

**Comment by szarkowicz** [comment]
Okay thanks - somehow I missed issue #77 that you previously answered.
