### ISSUE TITLE
Update BrainTree Drop In Script

### ISSUE THREAD

**Issue by selected-pixel-jameson** [srikanthonl/ngx-braintree#96]
The BrainTree Drop in UI Script needs to be updated. Currently version 1.8.0 is being used and the latest is version 1.12.0. PayPal can break when using versions older then 1.9.3.

**Comment by srikanthonl** [comment]
@selected-pixel-jameson thank you for the request. This is now updated and the latest version of ngx-braintree 6.1.4 is now published and comes with the latest version of dropin script 1.13.0.
