### ISSUE TITLE
We should be able to apply the CVV field

### ISSUE THREAD

**Issue by AlexandreBonfim** [srikanthonl/ngx-braintree#97]
Hi guys, we are able to apply Cardhold name but not able to show the cvv and check it as well.

**Comment by srikanthonl** [comment]
Hi,
CVV must be configured under settings in the dashboard of your Braintree account. There is nothing on the ngx-braintree side that can be done for this. Please enable it there and you should see CVV option. :) #77

**Comment by AlexandreBonfim** [comment]
Thanks for reply @srikanthonl! I just found it. Let me ask a question I checked all my backend code and I can't find the issue of the customer name. I'm populating it on the UI. When I check it on my sandbox the name is empty. Once again, thank you.

![screen shot 2018-10-08 at 12 54 01](https://user-images.githubusercontent.com/25756055/46605391-9e853e80-caf9-11e8-8442-1bad70bdd2ed.png)
