### ISSUE TITLE
How to Show Saved Card on Dropin UI ?

### ISSUE THREAD

**Issue by SumbulAfrozAli12** [srikanthonl/ngx-braintree#99]

**Comment by selected-pixel-jameson** [comment]
https://articles.braintreepayments.com/control-panel/vault/overview

**Comment by srikanthonl** [comment]
@selected-pixel-jameson thank you for your response. Yes, module has nothing to do with this. @SumbulAfrozAli12 just create a client token against the custmer id and you'll find all his saved payment details.
